[package]
name = 'UserInfo'
version = '1.0.0'
[dependencies.AptosFramework]
git = 'https://github.com/davidiw/aptos-core.git'
rev = 'conversions'
subdir = 'aptos-move/framework/aptos-framework'

[addresses]
sender = "0x88"